# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [19]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [20]:
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mukes/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mukes/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mukes/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mukes/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mukes/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mukes/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mukes/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mukes/anaconda3\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [21]:
a=np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [22]:
a.size*a.itemsize#size is array size and itemsize is the size of an element in the array

40

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [23]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [24]:
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [25]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [26]:
b[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [27]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [28]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [29]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [30]:
a=np.random.random(size=(3,3,3))
a

array([[[0.29903569, 0.40381242, 0.5918607 ],
        [0.44590841, 0.07911884, 0.2222168 ],
        [0.83349363, 0.84884337, 0.59605919]],

       [[0.96518343, 0.41696995, 0.01415874],
        [0.51406821, 0.50224115, 0.59927973],
        [0.32223217, 0.29040439, 0.35830922]],

       [[0.81367969, 0.21507722, 0.30950884],
        [0.62244249, 0.52948676, 0.34114605],
        [0.90011388, 0.91913943, 0.47884103]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [31]:
a=np.random.randint(0,9,size=(10,10))
print(a.max(),a.min())

8 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [32]:
a=np.random.randn(30)
a.mean()

0.007428154987623833

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [33]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
a


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [34]:
np.pad(a,2,)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [35]:
False
False
False
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [36]:
a=np.diag([0,1,2,3,4])
print(a)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [37]:
a=np.random.randint(4,8,size=(8,8))
a[::1,::2]=1
a[::1,1::2]=0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [38]:
a=np.random.randint(1,200,size=(6,7,8))
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [39]:
a=np.array([0,1])
np.tile(a,(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [40]:
a=np.random.random(size=(5,5))
norm=(a-a.min()/(a.max()-a.min()))
norm

array([[ 3.86862360e-01,  4.06788769e-01,  3.90559262e-01,
         7.17799305e-01,  4.57361840e-02],
       [ 8.41608198e-01, -7.61670193e-05,  2.78197297e-01,
         9.24930124e-01,  1.61654248e-01],
       [ 2.60978654e-02,  1.82655095e-01,  1.27811109e-01,
         8.57415327e-01,  4.78809945e-01],
       [ 6.57292343e-02,  3.59829838e-01,  5.71352169e-01,
         4.79976084e-01,  7.33681273e-01],
       [ 7.97570202e-01,  7.46255720e-01,  1.78156372e-01,
         7.66576808e-01,  8.11019250e-01]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [41]:
color=np.dtype([('R',np.ubyte,1),('G',np.ubyte,1),('B',np.ubyte,1),('A',np.ubyte,1)])
color

C:\Users\Mukes\AppData\Local\Temp/ipykernel_16592/2341170294.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([('R',np.ubyte,1),('G',np.ubyte,1),('B',np.ubyte,1),('A',np.ubyte,1)])


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [42]:
a=np.random.random(size=(5,3))
b=np.random.random(size=(3,2))
a@b

array([[0.47836387, 0.65270581],
       [0.33957491, 0.18998999],
       [0.40469389, 0.41642975],
       [0.19834878, 0.25799436],
       [0.53819915, 0.71096712]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [43]:
a=np.random.randint(0,20,size=10)
a[~((a>3)&(a<=8))]

array([12, 18, 16, 13, 15,  3, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
sum(range(5),-1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
Z**Z
Z<-Z
1j*Z

NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [47]:
a=np.random.randn(4)
b=np.copysign(np.ceil(np.abs(a)),a)
b

array([ 1., -2.,  1., -1.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [48]:
a=np.random.randint(0,4,size=6)
b=np.random.randint(0,4,size=6)
np.intersect1d(a,b)

array([0, 1, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [3]:
"np.seterr(all='ignore')"

"np.seterr(all='ignore')"

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
import numpy as np
np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\Mukes\AppData\Local\Temp/ipykernel_1544/4230900462.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [6]:
today=np.datetime64('today')
today-np.timedelta64(1),today,today+np.timedelta64(1)

(numpy.datetime64('2022-05-01'),
 numpy.datetime64('2022-05-02'),
 numpy.datetime64('2022-05-03'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [7]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [8]:
a=np.random.randn(5)
b=np.random.randn(5)
print('before a',a)
np.add(a,b,out=b)
np.negative(a,out=a)
np.divide(a,2,out=a)
np.multiply(b,a,out=a)
print('after a',a)

before a [-0.93433693  0.57147445 -1.00803553 -0.05742126  0.68737244]
after a [-0.60342854 -0.3222451   0.32430077  0.01741525 -1.04531082]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [9]:
a=np.random.random(5)
print('floor',np.floor(a))
print('ceil',np.ceil(a))
print('astype',a.astype(int))
print('trunc',np.trunc(a))
print('%',a-a%1)

floor [0. 0. 0. 0. 0.]
ceil [1. 1. 1. 1. 1.]
astype [0 0 0 0 0]
trunc [0. 0. 0. 0. 0.]
% [0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [10]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [11]:
a=np.arange(10)
for i in np.fromiter(a,int):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [12]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [13]:
np.sort(np.random.randint(1,5,size=10))

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 4])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [14]:
a=np.random.randint(3,5,size=(3,3))
np.add.reduce(a)

array([12, 11, 11])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [15]:
a=a=np.random.randint(3,5,size=(3,3))
b=a=np.random.randint(3,5,size=(3,3))
print(np.allclose(a,b))
np.array_equal(a,b)

True


True

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [16]:
a=np.random.random(5)
a.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [17]:
a=a=np.random.randint(1,9,size=(10,2))
r=lambda x:np.sqrt((x[0]**2)+(x[1]**2))
theta=lambda x:np.arctan2(x[1],x[0])*(180/np.pi)
print(r(a))
print(theta(a))

[8.54400375 5.09901951]
[69.44395478 78.69006753]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [18]:
a=np.random.random(10)
print(a)
a[np.argmax(a)]=0
a

[0.97819541 0.84781806 0.38072983 0.96070058 0.42021727 0.50348985
 0.5473855  0.34339144 0.35841227 0.18262429]


array([0.        , 0.84781806, 0.38072983, 0.96070058, 0.42021727,
       0.50348985, 0.5473855 , 0.34339144, 0.35841227, 0.18262429])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [19]:
x,y=np.random.randint(1,10,10).reshape(2,5)
print(x,y)
X,Y=np.meshgrid(x,y)
X, Y

[5 8 2 1 9] [4 9 8 2 3]


(array([[5, 8, 2, 1, 9],
        [5, 8, 2, 1, 9],
        [5, 8, 2, 1, 9],
        [5, 8, 2, 1, 9],
        [5, 8, 2, 1, 9]]),
 array([[4, 4, 4, 4, 4],
        [9, 9, 9, 9, 9],
        [8, 8, 8, 8, 8],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]]))

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [20]:
x=np.random.randint(1,10,size=6)
y=np.random.randint(1,10,size=6)
c=1/np.subtract.outer(x,y)
c

C:\Users\Mukes\AppData\Local\Temp/ipykernel_1544/3258854816.py:3: RuntimeWarning: divide by zero encountered in true_divide
  c=1/np.subtract.outer(x,y)


array([[        inf, -1.        ,  0.5       ,  0.33333333,  0.2       ,
         0.33333333],
       [-1.        , -0.5       ,  1.        ,  0.5       ,  0.25      ,
         0.5       ],
       [-0.25      , -0.2       , -0.5       , -1.        ,  1.        ,
        -1.        ],
       [-0.33333333, -0.25      , -1.        ,         inf,  0.5       ,
                inf],
       [ 0.5       ,  1.        ,  0.25      ,  0.2       ,  0.14285714,
         0.2       ],
       [-0.5       , -0.33333333,         inf,  1.        ,  0.33333333,
         1.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [21]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for ntype in [np.float16,np.float32,np.float64]:
    print(np.finfo(ntype).min)
    print(np.finfo(ntype).max)
    print(np.finfo(ntype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [22]:
np.set_printoptions(threshold=float('inf'))
a=np.random.randint(5,9,size=(16,20))
a

array([[6, 7, 6, 7, 5, 7, 7, 7, 5, 6, 8, 5, 8, 6, 5, 7, 8, 8, 7, 5],
       [6, 6, 5, 7, 8, 8, 6, 7, 7, 8, 7, 7, 5, 8, 8, 7, 8, 8, 7, 5],
       [5, 5, 8, 5, 8, 6, 5, 8, 5, 6, 8, 5, 6, 5, 8, 8, 6, 6, 7, 8],
       [5, 6, 5, 6, 7, 6, 7, 6, 8, 5, 8, 8, 8, 6, 5, 8, 5, 5, 5, 5],
       [7, 7, 7, 8, 5, 8, 5, 7, 8, 7, 5, 6, 5, 7, 8, 8, 8, 8, 6, 6],
       [7, 5, 6, 7, 7, 6, 8, 8, 5, 6, 8, 6, 5, 8, 7, 7, 7, 6, 8, 7],
       [7, 8, 8, 8, 6, 6, 8, 5, 6, 5, 8, 6, 6, 8, 5, 7, 6, 6, 5, 7],
       [6, 7, 6, 8, 5, 8, 8, 6, 5, 6, 7, 8, 6, 6, 6, 6, 7, 6, 5, 5],
       [5, 6, 7, 5, 5, 7, 8, 7, 8, 6, 6, 5, 5, 7, 6, 5, 6, 6, 6, 7],
       [6, 5, 5, 7, 7, 5, 5, 6, 6, 7, 8, 8, 6, 5, 8, 6, 6, 8, 6, 8],
       [6, 5, 5, 6, 8, 6, 7, 8, 5, 7, 8, 6, 7, 8, 7, 6, 6, 5, 7, 7],
       [6, 5, 5, 6, 5, 8, 5, 8, 7, 8, 7, 8, 5, 6, 8, 6, 7, 6, 7, 8],
       [6, 5, 6, 6, 7, 8, 5, 5, 5, 5, 7, 5, 5, 5, 6, 5, 7, 8, 5, 8],
       [5, 7, 8, 7, 5, 8, 8, 8, 6, 8, 5, 6, 7, 7, 7, 6, 5, 5, 5, 6],
       [5, 6, 6, 7, 7, 5, 8, 6, 6,

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [23]:
a=np.random.randint(1,100,100)
b=np.arange(100)
b[np.abs(a-b).argmin()]

12

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [24]:
DTYPE = np.dtype([('position', [('x', float, 1),
                                ('y', float, 1)], 1),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)], 1)])
np.zeros((1, 1), dtype=DTYPE)

C:\Users\Mukes\AppData\Local\Temp/ipykernel_1544/1031704725.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  DTYPE = np.dtype([('position', [('x', float, 1),


array([[((0., 0.), (0., 0., 0.))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [25]:
a=np.random.randint(0,100,size=(100,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
dist=np.sqrt(((x-x.T)**2)+((y-y.T)**2))
dist

array([[  0.        ,  63.63961031,  58.83026432,  32.24903099,
         36.01388621,  88.48163651,  42.95346319,  76.32168761,
         78.84795495,  36.67424164,  53.60037313,  23.19482701,
         70.26378868,  37.12142239,  80.21221852,  35.12833614,
         83.00602388,  15.03329638,  68.00735254,  73.02739212,
         11.70469991,  34.6554469 ,  23.76972865,  87.66413178,
         79.906195  ,  65.05382387,  56.22277119,  32.52691193,
         67.47592163,  88.19297024,  45.17742799,  32.69556545,
         28.7923601 ,  94.51454914,  17.4642492 ,  37.64306045,
         34.78505426,  86.00581376, 103.24727599,  32.75667871,
         31.25699922,  73.33484847,  51.66236541,  48.7954916 ,
         74.00675645,  57.28001397, 101.53324579,   7.21110255,
         72.        ,  55.97320788,  47.51841748,  34.92849839,
        102.42070103,  22.47220505,  78.10249676,  29.06888371,
         39.40812099,  60.41522987, 102.52804494,  33.10589071,
         58.69412236,  31.01612484,  99.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [26]:
a=np.float32(2)
a=a.astype(int,copy=False)
type(a)

numpy.int32

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [27]:
from io import StringIO
s=StringIO('''1, 2, 3, 4, 5 6,  ,  , 7, 8,  , 9,10,11''')
np.genfromtxt(s,delimiter=',')

array([ 1.,  2.,  3.,  4., nan, nan, nan,  7.,  8., nan,  9., 10., 11.])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [28]:
x=np.array([1,2,3])
for i,val in np.ndenumerate(x):
    print(i,val)
for i in np.ndindex(3,):
    print(i)

(0,) 1
(1,) 2
(2,) 3
(0,)
(1,)
(2,)


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [29]:
X,Y=np.meshgrid(np.linspace(0,5,4),np.linspace(0,5,4))
x=np.sqrt(X*X+Y*Y)
mu,sig=0.0,1.0
guass=np.exp((-(x-mu)**2)/2*(sig**2))
guass

array([[1.00000000e+00, 2.49352209e-01, 3.86592014e-03, 3.72665317e-06],
       [2.49352209e-01, 6.21765240e-02, 9.63975726e-04, 9.29249200e-07],
       [3.86592014e-03, 9.63975726e-04, 1.49453385e-05, 1.44069436e-08],
       [3.72665317e-06, 9.29249200e-07, 1.44069436e-08, 1.38879439e-11]])

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [30]:
a=np.arange(20).reshape(5,4)
b=np.random.choice(10,8)
print(b)
np.put(a,b,np.zeros(8))
a



[5 0 7 4 2 5 8 0]


array([[ 0,  1,  0,  3],
       [ 0,  0,  6,  0],
       [ 0,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [31]:
a=np.arange(20).reshape(4,5)
a-np.mean(a,axis=1,keepdims=True)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [32]:
a=np.random.randint(0,15,size=(4,5))
print(a)
a[np.argsort(a[:,2])]

[[ 8  3 10 14  5]
 [12  3  3  3  2]
 [ 7  6  7  5  0]
 [11  2  7 11  3]]


array([[12,  3,  3,  3,  2],
       [ 7,  6,  7,  5,  0],
       [11,  2,  7, 11,  3],
       [ 8,  3, 10, 14,  5]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [33]:
a=np.random.randint(0,2,size=(4,3))
print(a)
np.any(a,axis=0,where=np.isnan(a))

[[0 0 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]]


array([False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [34]:
a=np.random.randint(1,25,5)
b[np.abs(a-8).argmin()]

5

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [35]:
a=np.arange(4,7).reshape(1,3)
b=np.arange(8,11).reshape(3,1)
it=np.nditer([a,b,None])
for i,j,z in it:
    z[...]=i+j
it.operands

(array([[4, 5, 6]]),
 array([[ 8],
        [ 9],
        [10]]),
 array([[12, 13, 14],
        [13, 14, 15],
        [14, 15, 16]]))

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [36]:
class Foo:
    def __init__(self, name):
        self.name = name


x = Foo('spam')
x.name

'spam'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [37]:
a2 = [10, 11, 4, 6, 2, 1, 9]
a1 = [1, 3, 1, 3, 1, 2, 2]

np.bincount(a1,a2)

array([ 0., 16., 10., 17.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [38]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.array(np.bincount(I, X), dtype=int)
F

array([0, 7, 0, 6, 5, 0, 0, 0, 0, 3])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [39]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
colors.shape[0]

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [40]:
np.ones((2,2,2,2)).sum(axis=(-2,-1))

array([[4., 4.],
       [4., 4.]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [41]:
a = np.random.uniform(0, 1, 100)
b=np.random.randint(0,10,100)
sum_bin=np.bincount(b,weights=a)
counts=np.bincount(b)
sum_bin/counts

array([0.63397162, 0.65810412, 0.54264908, 0.51278698, 0.38288669,
       0.5366808 , 0.36184328, 0.61870894, 0.54697368, 0.48321294])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [42]:
np.diag(np.dot(np.ones((3,3)),np.zeros((3,3))))

array([0., 0., 0.])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [43]:
a=np.array([1,2,3,4,5])
b=np.zeros(17)
b[::4]=a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [44]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [45]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [46]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 77) ( 0, 94) ( 1, 68) ( 1, 94) ( 3, 20) ( 3, 50) ( 5, 35) ( 5, 96)
 (11, 13) (11, 47) (13, 47) (20, 50) (33, 38) (33, 79) (35, 96) (36, 72)
 (36, 78) (38, 79) (44, 73) (44, 74) (46, 62) (46, 95) (62, 95) (68, 94)
 (72, 78) (73, 74) (76, 84) (76, 95) (77, 94) (84, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [47]:
a = np.array([0, 2, 3, 1, 0])
np.repeat(np.arange(a.size), a)

array([1, 1, 2, 2, 2, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [48]:
from numpy.lib.stride_tricks import sliding_window_view
x = np.array([1, 2, 3, 4, 5])
sliding_window_view(x, window_shape=3).mean(axis=-1)

array([2., 3., 4.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [49]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(10)
sliding_window_view(Z, window_shape=3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [50]:
x = np.array([True])
np.logical_not(x, out=x)
x

array([False])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [51]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.43484254 13.20420422 14.45622256  7.4073983   7.73094126  2.04140497
  5.48635789  7.19478869  0.20353093  5.90284844]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [52]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
np.array([distance(P0, P1, p_i) for p_i in p])

array([[5.06317834e+00, 1.02252887e+01, 6.40667688e+00, 1.95046959e-01,
        2.70659352e+00, 1.81129185e+00, 2.42311191e+00, 1.44319321e+01,
        4.35771101e+00, 4.25448154e+00],
       [8.80620909e+00, 1.46924733e+01, 6.35049049e+00, 4.67881771e+00,
        6.55907513e+00, 9.51863127e-01, 2.23120219e+00, 1.35302687e+01,
        7.42135334e+00, 8.43270934e+00],
       [1.36038969e+01, 1.87702885e+01, 1.03878521e+01, 6.18738863e+00,
        1.12963558e+01, 6.37960962e-01, 5.78282880e+00, 1.69692497e+01,
        1.24159879e+01, 1.29125078e+01],
       [2.78856756e+00, 7.83140078e+00, 5.64095761e+00, 1.70469602e+00,
        4.04534730e-01, 2.49161949e+00, 4.78161156e+00, 1.40855379e+01,
        2.28812629e+00, 1.88585600e+00],
       [1.98668786e+00, 1.03645258e+01, 3.04951003e+00, 6.31083123e+00,
        4.22752683e-03, 7.78357608e+00, 6.66309216e-01, 4.54842258e+00,
        6.29427471e-01, 2.84524907e+00],
       [3.30868314e+00, 4.04746184e+00, 2.97697270e+00, 2.53158318e-02,
   

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [53]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 8 3 7 6 1 4 8 4 7]
 [5 7 7 7 1 2 8 4 3 0]
 [2 1 4 0 4 9 7 7 9 7]
 [4 0 6 4 0 4 3 5 2 7]
 [9 3 0 7 3 1 1 1 0 1]
 [5 2 2 8 5 2 2 4 8 1]
 [2 7 1 1 5 3 6 5 1 1]
 [7 7 0 9 3 6 5 7 7 4]
 [5 2 9 6 1 1 2 3 5 8]
 [4 5 3 8 4 4 5 2 0 8]]
[[0 0 0 0 0]
 [0 6 8 3 7]
 [0 5 7 7 7]
 [0 2 1 4 0]
 [0 4 0 6 4]]


C:\Users\Mukes\AppData\Local\Temp/ipykernel_1544/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [55]:
fZ = np.arange(1, 15, dtype=np.uint32)
sliding_window_view(Z, window_shape=4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [56]:
a=np.random.randint(1,9,size=(3,3))
np.linalg.svd(a)

(array([[-0.48033216,  0.52376067,  0.70353094],
        [-0.56360875,  0.4302754 , -0.70512996],
        [-0.67203139, -0.73521279,  0.08852099]]),
 array([17.69811875,  3.72732683,  1.97069208]),
 array([[-0.60888765, -0.38377534, -0.69424226],
        [ 0.49276611, -0.86883108,  0.04810531],
        [ 0.62164088,  0.31280833, -0.718132  ]]))

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [57]:
a=np.random.randint(1,4,size=(6))
print(a)
np.bincount(a).argmax()

[1 1 2 3 2 3]


1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [58]:
Z = np.random.randint(0, 5, (10, 10))
sliding_window_view(Z, window_shape=(3, 3))

array([[[[0, 2, 1],
         [1, 4, 4],
         [0, 3, 0]],

        [[2, 1, 0],
         [4, 4, 0],
         [3, 0, 3]],

        [[1, 0, 2],
         [4, 0, 3],
         [0, 3, 1]],

        [[0, 2, 0],
         [0, 3, 0],
         [3, 1, 2]],

        [[2, 0, 1],
         [3, 0, 3],
         [1, 2, 4]],

        [[0, 1, 4],
         [0, 3, 2],
         [2, 4, 2]],

        [[1, 4, 2],
         [3, 2, 1],
         [4, 2, 1]],

        [[4, 2, 4],
         [2, 1, 1],
         [2, 1, 2]]],


       [[[1, 4, 4],
         [0, 3, 0],
         [1, 2, 0]],

        [[4, 4, 0],
         [3, 0, 3],
         [2, 0, 0]],

        [[4, 0, 3],
         [0, 3, 1],
         [0, 0, 0]],

        [[0, 3, 0],
         [3, 1, 2],
         [0, 0, 0]],

        [[3, 0, 3],
         [1, 2, 4],
         [0, 0, 3]],

        [[0, 3, 2],
         [2, 4, 2],
         [0, 3, 4]],

        [[3, 2, 1],
         [4, 2, 1],
         [3, 4, 3]],

        [[2, 1, 1],
         [2, 1, 2],
         [4, 3, 2]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [59]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)


S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
S

Symetric([[ 6,  5, 10,  8,  5],
          [ 5,  2,  6,  6, 12],
          [10,  6,  2, 42,  9],
          [ 8,  6, 42,  2,  5],
          [ 5, 12,  9,  5,  1]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [60]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [61]:
Z = np.ones((16, 16))
k = 4
windows = sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [62]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] +
         Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    Z = iterate(Z)
Z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [63]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

Z[np.argsort(Z)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [64]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


cartesian(([1, 2, 3], [4, 5], [6, 7]))

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [65]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

np.power(x, 3)
x*x*x
np.einsum('i,i,i->i', x, x, x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [67]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
rows

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [68]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1), :]
U

[[0 1 1]
 [4 4 4]
 [2 1 3]
 [3 3 4]
 [3 2 0]
 [2 3 3]
 [3 4 1]
 [4 3 3]
 [2 3 0]
 [2 3 3]]
[[0 1 1]
 [2 1 3]
 [3 3 4]
 [3 2 0]
 [2 3 3]
 [3 4 1]
 [4 3 3]
 [2 3 0]
 [2 3 3]]


array([[0, 1, 1],
       [2, 1, 3],
       [3, 3, 4],
       [3, 2, 0],
       [2, 3, 3],
       [3, 4, 1],
       [4, 3, 3],
       [2, 3, 0],
       [2, 3, 3]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [69]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
B[:, ::-1]

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [70]:
Z = np.random.randint(0, 2, (6, 3))
T = np.ascontiguousarray(Z).view(
    np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
uZ

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [71]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)

array([[0.05106885, 0.2581403 , 0.32921329, 0.26688651, 0.06406908,
        0.25069024, 0.36819259, 0.33508181, 0.05831624, 0.1460052 ],
       [0.07831769, 0.39587641, 0.50487185, 0.40928934, 0.09825446,
        0.3844512 , 0.56464937, 0.51387164, 0.08943207, 0.22390929],
       [0.03218072, 0.16266553, 0.20745173, 0.16817689, 0.04037274,
        0.15797091, 0.2320143 , 0.21114974, 0.03674762, 0.09200428],
       [0.05920525, 0.29926777, 0.38166426, 0.30940745, 0.0742767 ,
        0.29063075, 0.42685383, 0.38846776, 0.06760731, 0.16926706],
       [0.06563208, 0.33175378, 0.42309453, 0.34299413, 0.08233956,
        0.32217919, 0.47318951, 0.43063657, 0.07494619, 0.18764127],
       [0.06510828, 0.32910611, 0.41971789, 0.34025675, 0.08168242,
        0.31960793, 0.46941306, 0.42719973, 0.07434806, 0.18614374],
       [0.09688978, 0.48975366, 0.62459604, 0.5063473 , 0.12155431,
        0.47561911, 0.69854908, 0.63573002, 0.1106398 , 0.27700664],
       [0.02436091, 0.12313832, 0.1570416

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [72]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200)  # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [73]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
X[M]

array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [74]:
X = np.random.randn(100)  # random 1D array
N = 1000  # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint

array([-0.14050785,  0.23108667])